In [2]:
import numpy as np
data = np.random.randn(2,3)
data

array([[ 0.5499326 , -0.17494583, -0.04316165],
       [-0.4700257 , -0.45177003,  1.43414372]])

In [3]:
data * 10

array([[ 5.49932605, -1.74945835, -0.43161649],
       [-4.70025699, -4.51770025, 14.34143718]])

In [4]:
data + data

array([[ 1.09986521, -0.34989167, -0.0863233 ],
       [-0.9400514 , -0.90354005,  2.86828744]])

In [5]:
data.shape

(2, 3)

In [6]:
data.dtype

dtype('float64')

In [7]:
data1 = [6, 7.5, 8 ,0 ,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [8]:
data2 = [[1, 2, 3], [5, 6, 7]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3],
       [5, 6, 7]])

In [9]:
arr2.ndim

2

In [10]:
arr2.shape

(2, 3)

In [11]:
arr1.dtype

dtype('float64')

In [12]:
arr2.dtype

dtype('int32')

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
np.empty((2, 3, 2))

array([[[1.13828208e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [6.23061762e-307, 3.80362947e+175]],

       [[1.51066871e+160, 4.18394445e-062],
        [4.03242517e+175, 3.60281893e+175],
        [3.83455832e+175, 3.53858920e-061]]])

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.dtype

dtype('int32')

In [19]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [20]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [21]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [22]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr.dtype

dtype('float64')

In [23]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [24]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [25]:
arr ** 3

array([[  1.,   8.,  27.],
       [ 64., 125., 216.]])

In [26]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [28]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [29]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [30]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])